---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Update image streams
      include_role:
        name: images
        tasks_from: import
      with_items:
        - 3scale
        - apicurito
        - codeready
        - enmasse
        - fuse
        - launcher
        - sso
        - webapp
      loop_control:
        loop_var: images_source_namespace